# -*- coding: utf-8 -*-
"""dictectory
"""

appdict = {
    # windows applications
    'StartMenue': '^DV2ControlHost',
    'WindowsFileSystem': '^CabinetWClass|^#32770 正在复制 \d* 个项目|^#32770 删除文件',
    'IE': '^IEFrame|^#32770 Windows Internet Explorer',
    'Notepad': '^Notepad',
    'WindowsPhotoViewer': '^Photo_Lightweight_Viewer',
    'TTPlayer': '^TTPlayer_|^#32770 千千静听',
    'WindowsConsole': '^ConsoleWindowClass',
    'TortoiseSVN': '.*TortoiseSVN$|.*- Commit - TortoiseSVN Finished!|^#32770 Commit -',
    'FunshionPlayer': '^funshion_player_tzdenjohn',
    'WindowsProgramManager': '^Progman Program Manager',
    'WindowsMediaPlayer': '^WMPlayerApp Windows Media Player',
    'DigitalPhotoProfessional': r'^ATL:0043D110 Digital Photo Professional|^#32770 Digital Photo Professional|^#32770 IMG_\d{4}\.CR2|^ATL:0043C3C0',
    'StormPlayer': '^Afx:400000:3:10003:2:',
    'MSN': '^IMWindowClass|.*Windows Live Messenger$|^MSBLWindowClass Windows Live Messenger',
    'PES': '.*Pro Evolution Soccer 2009',
    'QuickTime': '^QuickTimePlayerMain',
    'WinRAR': '^WinRarWindow',
    # Linux applications
    'BackInTime': '.*"Back In Time"',
    'Banshee': '^ "Nereid", "banshee-1"|^ "Banshee", "banshee"',
    'EyeOfGNOME': '^ "eog", "Eog"',
    'GnomeTerminal': '^ "gnome-terminal"',
    'Kpdf': '^ "kpdf"',
    'evince': '^ "evince", "Evince"',
    'Desktop': '^ "desktop_window"',
    'Nautilus': '^ "nautilus"|^ "file_properties", "Nautilus"|^ "file_progress", "Nautilus"  "File Operations"',
    'Gedit': '^ "gedit"',
    'GnomeSetting': '^ "gnome-control-center"|^ "gnome-appearance-properties"',
    'Inkscape': '^ "inkscape", "Inkscape"',
    'Mplayer': '^ "gnome-mplayer", "Gnome-mplayer"|^ "MPlayer", "MPlayer"|^ "Message", "MPlayer"',
    'Meld': '^ "meld", "Meld"',
    'RDesktop': '^ "rdesktop", "rdesktop"',
    'Rhythmbox': '^ "rhythmbox", "Rhythmbox"',
    'Totem': '^ "totem", "Totem"',
    'Transmission': '^ "transmission", "Transmission"',
    'Yast': '^ "y2controlcenter-gnome"|^ "y2base"',
    'FileRoller': '^ "file-roller", "File-roller"',
    'Synaptic': '^ "synaptic", "Synaptic"',
    'Guake': '^ "guake.py", "Guake.py"',
    'REP': '^ "rep.py", "Rep.py"',
    'Gnome-screenshot': '^ "gnome-screenshot", "Gnome-screenshot"',
    'Gnome-system-monitor': '^ "gnome-system-monitor", "Gnome-system-monitor"  "System Monitor"',
    'Ubuntu-Update-manager': '^ "update-manager", "Update-manager"',
    'Ubuntu-Software-Center': '^ "software-center", "Software-center"  "Ubuntu Software Center"',
    'unity-dash': '^  "unity-dash"',
    "Terminator": '^ "terminator", "Terminator"',
    'Groovy/Grails Tool Suite': '^ "Groovy/Grails Tool Suite", "Groovy/Grails Tool Suite"',
    'Xournal': '^ "xournal", "Xournal"',
    # Linux & Windows
    'AdobeReader': '.*Adobe Reader$|^ "acroread", "Acroread"',
    'Amule': '^ "amule", "Amule"',
    'Chrome': '^Chrome_|^ "Google-chrome", "Google-chrome"|^ "google-chrome", "Google-chrome"|^ "Google-chrome-stable", "Google-chrome-stable"',
    'GIMP': '.*GIMP\r$|^gdkWindowToplevel|^ "gimp-\d\.\d", "Gimp-\d\.\d"',
    'Firefox': '^ ".*", "Firefox"|^ ".*", "Firefox-bin"|^ ".*", "Shiretoko"|.* - Mozilla Firefox|MozillaUIWindowClass Mozilla Firefox',
    'Git': '^ "git-gui", "Git-gui"|^ "gitk", "Gitk"|^ "git-cola", "Git-cola"',
    'GoogleEarth': '^ "googleearth-bin", "Googleearth-bin"',
    'JabRef': '^ ".*", "net-sf-jabref-JabRefMain"  ".*"',
    'Matlab': '.*"MATLAB  7.6.0 (R2008a)"|^ "sun-awt-X11-XFramePeer", "com-mathworks-util-PostVMInit"',
    'NetBeans': '.*NetBeans IDE \d\.\d"',
    'NaoTHRobotControl': '.*RobotControl for Nao|^ "sun-awt-X11-XDialogPeer", "de-hu_berlin-informatik-ki-nao-Main"',
    'XABSLEditor': '^ "sun-awt-X11-XFramePeer", "de-hu_berlin-informatik-ki-jxabsleditor-Main"',
    'Emacs': '^Emacs|^ "emacs"|^ "emacs-snapshot"|^ ".*", "Emacs"|^ "emacs24", "Emacs24"',
    'QQ': '^TXGuiFoundation|^ "qq"',
    'OpenOffice': '^ "VCLSalFrame", "OpenOffice.org \d\.\d"|.*OpenOffice.org Calc$',
    'SimSpark': '^ "simspark", "simspark"|^ "rcssmonitor3d", "rcssmonitor3d"  "SimSpark"|^ "rsgedit", "Rsgedit"|^ "rcssserver3d", "rcssserver3d"',
    'Skype': '^ "skype"|^ tSkMainForm.UnicodeClass Skype',
    'Pidgin': '^ "pidgin"|^ "Pidgin"',
    'Python': '^TkTopLevel|^Shell_TrayWnd|^ "python"',
    'Picasa': '^ytWindow|^ "Picasa3.exe", "Wine"',
    'Webots': '^ "webots", "Webots"',
    'Evolution': '^ "evolution", "Evolution"',
    'Thunderbird': '^ ".*", "Thunderbird"',
    'QtCreator': '^ "qtcreator", "QtCreator"',
    'QtAssistant': '^ "assistant", "Assistant"',
    "Zim": '^ "zim", "Zim"',
    'Keepassx': '^ "keepassx", "Keepassx"',
    'VirtualBox': '^ "Qt-subapplication", "VirtualBox"',
    'Openscad': '^ "openscad", "Openscad"',
    'Meshlab': '^ "meshlab", "Meshlab"',
    'Blender': '^ "Blender", "Blender"',
    'FreeCAD': '^ "freecad", "Freecad"',
    'Texworks': '^ "texworks", "Texworks"',
    }

categoryDict = {
    'InternetBrowser': 'Firefox|Chrome|IE',
    'Email': 'Evolution|Thunderbird',
    'Downloader': 'Amule|Transmission',
    'Editor': 'Emacs|Notepad|Gedit',
    'Note': 'Zim|Xournal',
    'PdfReader': 'Kpdf|AdobeReader|evince',
    'Console': 'WindowsConsole|GnomeTerminal|Guake|Terminator',
    'Messanger': 'QQ|Pidgin|Skype|MSN',
    'Video': 'WindowsMediaPlayer|Totem|MPlayer|QuickTime',
    'Music': 'StormPlayer|TTPlayer|Banshee|Rhythmbox',
    'SystemUtilities': 'WindowsFileSystem|Nautilus|GnomeSetting|Yast|WindowsProgramManager|StartMenue|FileRoller|Synaptic|WinRAR|Rdesktop|Gnome-screenshot|Gnome-system-monitor|Keepassx|VirtualBox|Ubuntu-Update-manager|unity-dash|Ubuntu-Software-Center',
    'Office': 'OpenOffice|JabRef|Texworks',
    'Photography': 'DigitalPhotoProfessional|WindowsPhotoViewer|GIMP|Picasa|EyeOfGNOME|Inkscape',
    'DevTools': 'TortoiseSVN|Python|NetBeans|NaoTHRobotControl|Git|Meld|Matlab|XABSLEditor|REP|QtCreator|QtAssistant|Groovy/Grails Tool Suite',
    'Simulation': 'Webots|SimSpark',
    '3DDesign': 'Openscad|Meshlab|Blender|FreeCAD',
    'Game': 'PES',
    }
